# config/cucumber.yml
##YAML Template
---
# Change ENVIRONMENT to 'TEST' or 'DEV' or 'PROD'
# and ensure the corresponding
#default: --format progress --format html --out reports/<%= Time.now.strftime("%Y%m%d-%H%M%S") %>-report.html ENVIRONMENT=TEST
#default: --format pretty --format json --out=cucumber.json ENVIRONMENT=TEST --format rerun --out tmp/rerun.txt
default: --format pretty --format json --out=cucumber.json ENVIRONMENT=TEST
allure_report: --format AllureCucumber::Formatter ENVIRONMENT=TEST --tags ~@manual



